export enum UserSettings {
    notificationCollaboration = "notification_collaboration",
    notificationComment = "notification_comment",
    notificationReply = "notification_reply",
    notificationFollow = "notification_follow",
    notificationLike = "notification_like",
    notificationRepost = "notification_repost",
    notificationSale = "notification_sale",
    paypalMail = "paypalMail",
    publicLikes = "publicLikes",
    theme = "theme",
    streamingQuality = "streamingQuality",
    playFromAutoQueue = "playFromAutoQueue",
    language = "language",
}
