import {TrackLike} from "./TrackLike";
import {Album} from "./Album";
import {Playlist} from "./Playlist";
import {Notification} from "./Notification";
import {Comment} from "./Comment";
import {TrackCollaborator} from "./TrackCollaborator";
import {User} from "./User";
import {Repost} from "./Repost";
import {InteractionMetadata} from "../../InteractionMetadata";
import {Entity} from "@targoninc/ts-search";
import {Visibility} from "../../../Enums/Visibility";

export interface Track extends Entity {
    repost_user_id?: number;
    repost?: Repost;
    collab?: TrackCollaborator;
    user?: User;
    playlists?: Playlist[];
    albums?: Album[];
    notifications?: Notification[];
    collaborators?: TrackCollaborator[];
    user_id: number;
    title: string;
    isrc: string;
    artistname: string;
    upc: string;
    visibility: Visibility;
    credits: string;
    loudness_data: string;
    genre: string;
    version: string;
    versionid: number;
    length: number;
    description: string;
    release_date: Date;
    updated_at: Date;
    created_at: Date;
    plays: number;
    secretcode: string;
    monetization: boolean;
    price: number;
    has_cover: boolean;
    processed: boolean;
    file_hash?: string;
    file_fingerprint?: string;
    likes?: InteractionMetadata<TrackLike>;
    reposts?: InteractionMetadata<Repost>;
    comments?: InteractionMetadata<Comment>;
}

